### ISSUE TITLE
`log_file_from_path` goes to the right recording but overrides the app_id

### ISSUE THREAD

**Issue by EtaLoop** [rerun-io/rerun#8039]
**Describe the bug**
Here, I want to log a supported file (obj) in the "my_app" recording. But with `log_file_from_path`, this logs to a "/path/to/file/file.obj" recording.
Removing `log_file_from_path` make it logs correctly to "my_app". So, my guess was that, it renames the recording to the file path?

Is it me doing something wrong here, or no?

I'm on Rerun 0.19.1.
**Code :**
```py
import rerun as rr

def main():
    rec = rr.init("my_app", spawn=True)
    
    rr.log(
        "triangle",
        rr.Mesh3D(
            vertex_positions=[[0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 0.0]],
            vertex_normals=[0.0, 0.0, 1.0],
            vertex_colors=[[0, 0, 255], [0, 255, 0], [255, 0, 0]],
            triangle_indices=[2, 1, 0],
        ),
        recording=rec,
    )
    
    rr.log_file_from_path(file_path="/pah/to/file/file.obj", recording=rec)
```

**Comment by teh-cmc** [comment]
You are _not_ doing anything wrong, this is one of the many subtle data-loading bugs that were fixed in:
* https://github.com/rerun-io/rerun/pull/7966

These fixes will ship in 0.20, which is right around the corner (ish).

If you cannot wait for 0.20, you can try using one of our nightly builds instead: https://github.com/rerun-io/rerun/releases/tag/prerelease

**Comment by EtaLoop** [comment]
Oh, great ! Thanks

**Comment by qianyizhang** [comment]
> You are _not_ doing anything wrong, this is one of the many subtle data-loading bugs that were fixed in:
> 
> * [Consistent open/import/log_file behaviors in all common scenarios #7966](https://github.com/rerun-io/rerun/pull/7966)
> 
> These fixes will ship in 0.20, which is right around the corner (ish).
> 
> If you cannot wait for 0.20, you can try using one of our nightly builds instead: https://github.com/rerun-io/rerun/releases/tag/prerelease

I am working with 0.20, still doesn't overwrite the application_id as intended 😣

**Comment by qianyizhang** [comment]
another related issue https://github.com/rerun-io/rerun/issues/8167

**Comment by teh-cmc** [comment]
> > You are _not_ doing anything wrong, this is one of the many subtle data-loading bugs that were fixed in:
> > 
> > * [Consistent open/import/log_file behaviors in all common scenarios #7966](https://github.com/rerun-io/rerun/pull/7966)
> > 
> > These fixes will ship in 0.20, which is right around the corner (ish).
> > If you cannot wait for 0.20, you can try using one of our nightly builds instead: https://github.com/rerun-io/rerun/releases/tag/prerelease
> 
> I am working with 0.20, still doesn't overwrite the application_id as intended 😣

I can confirm the script posted in this issue works as expected on 0.20:
![image](https://github.com/user-attachments/assets/ab4ebcff-7b9d-4bd5-9d2d-bb26b5d194d1)
