### ISSUE TITLE
Improve camera zoom via mouse wheel

### ISSUE THREAD

**Issue by Wumpf** [rerun-io/rerun#965]
The smaller the camera distance, the smaller the orbit camera movement via scroll wheel should be (3d space view)
This is already the case, but it's often still hard to accurately zoom in.

Demonstration of problem on Linux:

https://user-images.githubusercontent.com/3312232/217645337-4c45cc65-37d3-45c3-88f4-f379b30e2916.mov

**Comment by emilk** [comment]
Maybe related:
* https://github.com/emilk/egui/issues/2718

**Comment by jleibs** [comment]
This has gotten somewhat better on native recently, but it's noticeably much much worse on web.

**Comment by jleibs** [comment]
This is still quite broken on web. Here's video of scrolling a single step with scroll-wheel on linux.

https://github.com/rerun-io/rerun/assets/3312232/8206549f-f2b6-4294-8f74-879d4929b3a5

**Comment by emilk** [comment]
Here it is on Web on my Mac, scrolling one mouse step at a time (on my mouse):

![scroll-step-web](https://github.com/rerun-io/rerun/assets/1148717/7f21beff-a159-4ea9-b4b8-98eb2876384c)

It is pretty worrying that the `wheel` event acts so differently on different platforms. The eframe code handling this is platform agnostic:

https://github.com/emilk/egui/blob/073f49682da20828dbd118f1d97e14a2b3879631/crates/eframe/src/web/events.rs#L390-L438

Btw, why isn't the scroll smoothed @Wumpf? I know you added code for that, and if I scroll faster I get the smoothed behavior, but @jleibs doesn't. Perhaps he get many duplicates of the wheel events?

This is what I see under the "Inspection -> Input" panel in egui.rs when I scroll very quickly with a mouse wheel:

![IMG_5224](https://github.com/rerun-io/rerun/assets/1148717/2d7cc893-0a82-4140-8c20-a95731501821)

Here I get eight scroll lines in one go. If I scroll slower I only get one scrol line at a time (as expected).

**Comment by emilk** [comment]
Please try https://github.com/rerun-io/rerun/pull/4668 on Linux and see how zooming feels these days

**Comment by Wumpf** [comment]
done!

**Comment by jleibs** [comment]
The above issues are still present:

This is one wheel click forward/backward:

https://github.com/rerun-io/rerun/assets/3312232/0ffd790a-31de-4645-87c0-bf4ca3a78147

**Comment by jleibs** [comment]
![image](https://github.com/rerun-io/rerun/assets/3312232/b69ba515-4b1b-47ba-b262-211d8078c972)

**Comment by Wumpf** [comment]
egui.rs also gives me points but shows +/- 13 for a single notch on the scroll wheel
